# @server = https://humble-guacamole-49g746r44qhqww9-5000.app.github.dev

@server = http://localhost:5000
@users-server =  https://ddd-in-language.aardling.eu
@users-server-token = emk7srgDuZ

### Root
GET {{server}}/

### Start Scenarion
POST {{server}}/startScenario

### CalculatePrice
POST {{server}}/calculatePrice
{
  "date": "2023-07-23",
  "dropped_fractions": [
    {
      "amount_dropped": 83,
      "fraction_type": "Green waste"
    },
    {
      "amount_dropped": 18,
      "fraction_type": "Construction waste"
    }
  ],
  "person_id": "Squirrel Gus",
  "visit_id": "1"
}

### Retrieve users
GET {{users-server}}/api/users
content-type: application/json
x-auth-token: {{users-server-token}}
x-workshop-id: ImplementingTacticalPatternsDDDEU24


